# Generated by Django 4.1.3 on 2022-11-03 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_blog_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='rate',
            field=models.CharField(blank=True, choices=[('2', '💓'), ('1', '💙'), ('0', '💔')], max_length=255),
        ),
    ]
