# Generated by Django 4.1.3 on 2022-11-22 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0009_alter_tags_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='rate',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
