# Generated by Django 4.1.3 on 2022-11-22 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0010_alter_blog_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='blog',
            name='voted',
            field=models.IntegerField(default=1),
        ),
    ]
