# Generated by Django 4.1.3 on 2022-11-22 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0011_alter_blog_rate_alter_blog_voted'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='analysis',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
