# Generated by Django 4.1.3 on 2022-11-25 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0023_reactionhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reactionhistory',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
