# Generated by Django 4.1.3 on 2022-11-27 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0025_alter_blog_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='featured_image',
            field=models.ImageField(blank=True, default='profiles/default.png', null=True, upload_to=''),
        ),
    ]
