# Generated by Django 4.1.3 on 2022-11-28 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0028_blockedcontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockedcontent',
            name='blog',
            field=models.ManyToManyField(blank=True, to='blogs.blog'),
        ),
    ]
