# Generated by Django 4.1.3 on 2022-11-28 12:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_profile_bio'),
        ('blogs', '0029_alter_blockedcontent_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('saved_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('blog', models.ManyToManyField(blank=True, to='blogs.blog')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
            options={
                'ordering': ('-saved_on',),
            },
        ),
    ]
