# Generated by Django 4.1.3 on 2022-11-28 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_messages'),
        ('blogs', '0031_followable_blocked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockedcontent',
            name='blocker',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
    ]
